import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../styles/globals.css";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={lato.style}
        className="flex h-[100dvh] w-full flex-col items-center gap-3 bg-plum-900"
      >
        {children}
      </body>
    </html>
  );
}
