name: CI
on:
  pull_request:
    branches:
      - homolog
      - main

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Type-And-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup npm run
        uses: npm run/action-setup@v3.0.0
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm run"

      - name: Install dependencies
        run: npm run install --frozen-lockfile

      - name: Check TS types
        run: npm run run check-types

      - name: Lint
        run: npm run run lint

  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup npm run
        uses: npm run/action-setup@v3.0.0
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm run"

      - name: Install dependencies
        run: npm run install --frozen-lockfile

      - name: Test
        run: npm run test:unit

  E2E-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup npm run
        uses: npm run/action-setup@v3.0.0
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm run"

      - name: Install dependencies
        run: npm run install --frozen-lockfile

      - name: Install playwright deps
        run: npx playwright install --with-deps

      - name: E2E test
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
