name: CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Type-And-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Check TS types
        run: npm run check-types

      - name: Lint
        run: npm run lint

  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test:unit

  E2E-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Install playwright deps
        run: npx playwright install --with-deps

      - name: E2E test
        run: npm run test:e2e

      - uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
